image: Windows Server 2012 R2

install:
  - C:\MinGW\bin\mingw-get install gcc

build_script:
  - bash -c "compgen -c | grep gcc"
  - bash -c "find . -name '*gcc*'"
  - bash -c "gcc --version"
  - mvn clean install --batch-mode


