image: Windows Server 2012 R2

#install:
#  - C:\MinGW\bin\mingw-get install gcc

build_script:
  - bash -c "mkdir -p /c/projects/crashjvm/target/classes/nativelibs/amd64/"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - cl.exe src\main\java\uk\me\mjt\CrashJvm.c /I %JAVA_HOME%\include /I %JAVA_HOME%\include\win32 -FeCrashJvm.dll -MD -LD
  - copy CrashJvm.dll target\classes\nativelibs\amd64\
  - dir target\classes\nativelibs\amd64\
#/link /DLL /out:target\classes\nativelibs\amd64\CrashJvm.dll
  - mvn install --batch-mode

test:
  - bash test.sh
