image: Windows Server 2012 R2

#install:
#  - C:\MinGW\bin\mingw-get install gcc

build_script:
  - mkdir x86
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - cl.exe src\main\java\uk\me\mjt\CrashJvm.c /I %JAVA_HOME%\include /I %JAVA_HOME%\include\win32 -Fex86\CrashJvm.dll -MD -LD

  - mkdir amd64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - cl.exe src\main\java\uk\me\mjt\CrashJvm.c /I %JAVA_HOME%\include /I %JAVA_HOME%\include\win32 -Feamd64\CrashJvm.dll -MD -LD

  - mvn install --batch-mode

test_script:
  - bash test.sh

artifacts:
  - path: amd64\CrashJvm.dll

deploy:
    # Amazon S3 deployment provider settings
  - provider: S3
    access_key_id: AKIAI7AXAB7QKGPVNYVA
    secret_access_key:
      secure: snxWY4w58Q5StGc6YVIw4MQe3BeqV0eAJ5nANkccZzC70PumRa+fGkBEsg960bFo
    bucket: artifacts.mjt.me.uk
    region: eu-west-1
    folder: crashjvm
    artifact: amd64\CrashJvm.dll
    set_public: false

