image: Windows Server 2012 R2

#install:
#  - C:\MinGW\bin\mingw-get install gcc

build_script:
  - bash -c "pwd"
  - bash -c "/C/MinGW/bin/gcc.exe --version"
  - bash -c "mkdir -p /c/projects/crashjvm/target/classes/nativelibs/amd64/"
  - bash -c "/C/MinGW/bin/gcc.exe -o /c/projects/crashjvm/target/classes/nativelibs/amd64/CrashJvm.dll /c/projects/crashjvm/src/main/java/uk/me/mjt/CrashJvm.c"
  - mvn clean install --batch-mode


